package main

import (
	"os"
	"path/filepath"
	"testing"
)

func TestReadChecksum(t *testing.T) {
	dir := t.TempDir()
	body := `# generated by sha256sum -b
abc123def4567890abcdef1234567890abcdef1234567890abcdef1234567890  vpsguard-linux-amd64
fedcba0987654321fedcba0987654321fedcba0987654321fedcba0987654321 *vpsguard-linux-arm64
deadbeef0987654321deadbeef0987654321deadbeef0987654321deadbeef00  ./vpsguard_0.4.0_amd64.deb
malformed line with one field only
`
	path := filepath.Join(dir, "checksums.txt")
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}

	cases := map[string]string{
		"vpsguard-linux-amd64":      "abc123def4567890abcdef1234567890abcdef1234567890abcdef1234567890",
		"vpsguard-linux-arm64":      "fedcba0987654321fedcba0987654321fedcba0987654321fedcba0987654321",
		"vpsguard_0.4.0_amd64.deb":  "deadbeef0987654321deadbeef0987654321deadbeef0987654321deadbeef00",
	}
	for name, want := range cases {
		got, err := readChecksum(path, name)
		if err != nil {
			t.Errorf("%s: %v", name, err)
			continue
		}
		if got != want {
			t.Errorf("%s: got %q, want %q", name, got, want)
		}
	}

	if _, err := readChecksum(path, "missing-file"); err == nil {
		t.Error("missing entry should error")
	}
}

func TestFileSHA256(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "x")
	if err := os.WriteFile(path, []byte("hello"), 0o600); err != nil {
		t.Fatal(err)
	}
	got, err := fileSHA256(path)
	if err != nil {
		t.Fatal(err)
	}
	want := "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRegexEscape(t *testing.T) {
	cases := map[string]string{
		"ceorkm/vpsguard":         "ceorkm/vpsguard",
		"foo.bar/baz":             `foo\.bar/baz`,
		"a+b":                     `a\+b`,
		"x(y)":                    `x\(y\)`,
	}
	for in, want := range cases {
		if got := regexEscape(in); got != want {
			t.Errorf("regexEscape(%q) = %q, want %q", in, got, want)
		}
	}
}
